Code: Assignment2-Part2

In [1]:
import vugrad as vg
import numpy as np

In [21]:
x = vg.TensorNode(np.random.randn(2,2))

In [34]:
np.random.seed(0)
a = vg.TensorNode(np.random.randn(2,2))
b = vg.TensorNode(np.random.randn(2,2))
c = a + b
print(a.value)
print(b.value)

[[1.76405235 0.40015721]
 [0.97873798 2.2408932 ]]
[[ 1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721]]


In [35]:
print(c.value)

[[ 3.63161034 -0.57712067]
 [ 1.9288264   2.08953599]]


In [39]:
source_node = c.source
source_value_0 = c.source.inputs[0].value
print(source_node)
print(source_value_0)

[[1.76405235 0.40015721]
 [0.97873798 2.2408932 ]]


In [10]:
print(c.source.inputs[0])

TensorNode[size (2, 2), source None].


In [40]:
print(c.grad)

[[0. 0.]
 [0. 0.]]
